### ISSUE TITLE
Thank you for providing the schematic and firmware!

### ISSUE THREAD

**Issue by FunDeckHermit** [jetperch/js220_evk1#1]
Could you consider enabling discussions for this repository?

**Comment by mliberty1** [comment]
Thanks for the suggestion @FunDeckHermit .  Created!  I have not yet used GitHub Discussions, so hopefully it goes well.  This should be a great place for focused EVK1 topics.  For more general Joulescope discussions, the [Joulescope forum](https://forum.joulescope.com/) is still the best place.
